### ISSUE TITLE
Fix y axis on graphs with %s

### ISSUE THREAD

**Issue by nhuber** [airbnb/caravel#114]
When you have a graph with y axis between 0 and 1 it appears to show them in "m"

<img width="469" alt="screen shot 2016-01-14 at 11 22 28 am" src="https://cloud.githubusercontent.com/assets/724287/12334844/1d948fde-bab1-11e5-9cc9-d4829df942fb.png">

All of these should really be their "m" value / 10 and in percent. So the top line is in reality values of around 6%

**Comment by mistercrunch** [comment]
Yeah, the `m` for "micro" is confusing. The solution to that is using the d3 Y axis formatting in the form. It's not super intuitive but it's very flexible. Maybe I should have a free form dropdown with common suggestions instead of the current free form field:
<img width="234" alt="screen shot 2016-01-14 at 11 44 56 am" src="https://cloud.githubusercontent.com/assets/487433/12336088/604248ac-bab7-11e5-982e-06c62b162663.png">

**Comment by nhuber** [comment]
Perfect. Maybe just make % the default for <1 values or something

**Comment by mistercrunch** [comment]
Fixed.
