### ISSUE TITLE
Initial selection for sunburst graph

### ISSUE THREAD

**Issue by gbrian** [airbnb/caravel#215]
Hi there,

I've added a few lines to sunburst to change the way it's initially painted, now it shows the first path.

![image](https://cloud.githubusercontent.com/assets/767180/14166010/a2cd7aae-f70f-11e5-8c00-8aace9811cca.png)

Makes sense to add a new setting kind of "always show main path" ?
Thanks

PS: Just did this:

```
// Initial selection
      var mainpath = function(){
        var c = tree.children[0];
        while(c.hasOwnProperty('children') && c.children.length != 0)
            c = c.children[0];
        return c;
      }
      highlighpath(mainpath());
```

**Comment by williaster** [comment]
Nice. I don't have a strong opinion on this, I'd say go for it if you think it'd be useful. @mistercrunch? 

Since it's so easy to update on mouseover I also don't have a strong opinion on if there needs to be a toggle at all, it could just always do this? If you want to add a toggle you'll have to get into python land, see any vis in `viz.py` and you can see how the form controls are added. Then add the check for toggle state on the JS side. Encapsulating all of the highlighting into a `highlightPath()` function is cool.

**Comment by mistercrunch** [comment]
Sorry about the delay. I think people might go either way on this one, though having an actual option to preselect a specific one may be marginally useful, arbitrarily selecting the first one doesn't seem that useful to me.

**Comment by gbrian** [comment]
Idea behind this was to show the `main path`, the one with highest percentage.
At the same time the graph is shown with more data from the first refresh, as I plan to have it self refreshed is useful to have it showing that path.
I'm planning to keep last user selections as well...and maybe allow double selection to have a two paths comparison...but maybe that's only usegul for me ;)
