### ISSUE TITLE
How to run this with nginx & uwsgi?

### ISSUE THREAD

**Issue by COLABORATI** [airbnb/caravel#456]
Ok, I am a little bit confused about the many options on how to run python webapps, unfortunately there is no one zen way of doing this. There are some tutorials out there that explain how to run a simple flask app, however none of them explains how to do this if the flask app is a python package that was installed with pip. 

It would be really great if you could add a few lines of documentation of how to run caravel behind an nginx + uwsgi setup, thanks!

**Comment by mistercrunch** [comment]
We just run the gunicorn server in production, though it's behind an nginx reverse proxy that takes care of authentication and load balancing and we're happy with that setup. 

If you don't like the gunicorn approach, perhaps you want to make your own builds (I think it's just about running `npm run prod` from the assets folder) an run off the file system instead of the pip package. Once you do, feel free to contribute your process in our docs, though I think running flask apps on nginx is well documented already.

**Comment by COLABORATI** [comment]
Right, I now understand that there is already gunicorn that comes with caravel out of the box. No need for uwsgi.
