### ISSUE TITLE
caravel uninstall

### ISSUE THREAD

**Issue by yasinsancaktutan** [airbnb/caravel#511]
Hi all,

I tried to upgrade from version 0.8.9 to 0.9.0, app looks updated but there are issues about database (e.g some missing columns)

I tried to update database too using "caravel db upgrade" but no luck.. how can i uninstall caravel completely to try a clean install?

I also tried "pip uninstall caravel" but that didn't work.

Thanks in advance.

**Comment by xrmx** [comment]
@yasinsancaktutan i think you need to be more specific on what did not work in order to help you. What is `caravel db upgrade` and `pip uninstall caravel` output? If you want to start from scratch just use a different virtualenv, if do not care about losing your data drop the db. There's nothing caravel specific :)

**Comment by mistercrunch** [comment]
Was not specific enough, reopen with more details.
