### ISSUE TITLE
[dashboard] make the widget header clickable and lead to the explore for that slice

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/caravel#578]

**Comment by ascott** [comment]
the title for a slice on a dashboard should link to the explore view for that slice.

we will have to decide how to treat the header in this case to indicate that it's a link. maybe hover with lighter gray? or maybe no change in state and just the pointer cursor. 

<img width="572" alt="screenshot 2016-08-23 20 44 35" src="https://cloud.githubusercontent.com/assets/130878/17917515/2678a50c-6972-11e6-9544-93c95ad347d9.png">

**Comment by vera-liu** [comment]
- found that if slice name in the header is made clickable, it conflicts with the hover-to-show feature of chart-controls on the right of the header. One way to do this is making the chart-controls constantly shown, losing the hover-to-show feature. Like this:
![screen shot 2016-08-29 at 1 18 21 pm](https://cloud.githubusercontent.com/assets/20978302/18066054/7f2eb178-6deb-11e6-8f69-3e62942eb69c.png)

 - After discussing with Alanna, the hover-to-show feature of chart-controls is more important since many users don't need the control toolbar, also 'explore' is available in the toolbar which adapts the current user-flow. So we might close this one without changing?
