### ISSUE TITLE
caravel db upgrade(windows)

### ISSUE THREAD

**Issue by joysam1510** [airbnb/caravel#689]
Does anyone know how to install caravel successfully on windows 10?

C:>caravel db upgrade
'caravel' is not recognized as an internal or external command,
operable program or batch file.

C:>python caravel db upgrade
python: can't open file 'caravel': [Errno 2] No such file or directory

C:\Anaconda3\Lib\site-packages\caravel\bin
The system cannot find the path specified

**Comment by xrmx** [comment]
I think it's not supposed to work outside a unix environment. Gunicorn, for start, does not run on windows.

**Comment by bf16574403** [comment]
Windows... Windows... Windows...!! its a necessary evil, and you will have to do it at some point in time.

**Comment by alanmcruickshank** [comment]
@bf16574403 do you realise that caravel is designed to run on a server
rather than the users local computer? In our deployment caravel runs on an
AWS cloud server and then multiple users (many of them on windows) access
it via their browser from there. From a user perspective, caravel is
already windows compatible (and android and iOS and anything else with an
internet browser). The Unix requirement is for the machine that actually
hosts the application, which are already generally Unix machines. If you're
only running windows servers then its very straightforward to set up a
virtual box and run caravel within that.

I think that might be where the confusion is coming from.

On Thu, 30 Jun 2016 00:43 bf16574403, <notifications@github.com> wrote:

> Windows... Windows... Windows...!! its a necessary evil, and you will have
> to do it at some point in time.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/airbnb/caravel/issues/689#issuecomment-229521799>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEdFuGKnGwzD1IuDY0NJIrIwCRnRoc4Lks5qQwMxgaJpZM4JAumT>
> .
>
-- 

_______
Alan Cruickshank
E: alanmcruickshank@gmail.com
T: +44 770 6851825

**Comment by bf16574403** [comment]
alanmcruickshank I do indeed realise that Caravel is for a server type environment and not local desktop install. What I am saying is if JIRA, docker, Pentahoe (and other Apache based apps)etc can install and run on windows without need for containers then it makes evolutionary sense that Caravel go down that path too... I raise these points only out of admiration for Caravel , and yes it would broaden the user base and community...

**Comment by mistercrunch** [comment]
We will review and merge Windows compatibility PRs. I can guarantee you that we won't drive it though as we don't have any Windows around.
