### ISSUE TITLE
ERROR about "fabmanager create-admin --app caravel"

### ISSUE THREAD

**Issue by SevnChen** [airbnb/caravel#717]
when i create an admin user: fabmanager create-admin --app caravel。 i get:

c:\anaconda2\lib\site-packages\flask_cache\__init__.py:152: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
2016-07-04 17:19:01,871:ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (sqlite3.OperationalError) unable to open database file

**Comment by xrmx** [comment]
@SevnChen caravel is supposed to run on unix like systems and not on windows

**Comment by xrmx** [comment]
@SevnChen sure, but "it isn't officiallly supported" means you have to help yourself in fixing issues and not just open issues :)
But again i cannot see how this can work *easily* if gunicorn does not work on windows.

**Comment by aljones** [comment]
The sqlite error is because the caravel_config does not specify a valid windows path for the db file.
Try something like `sqlite:///C:\\path\\to\\database.db`

If you haven't setup your caravel_config.py file you'll probably need to specify the pythonpath enironment variable so that it can be found.

The cryptography instructions are out of date.  You can just pip install cryptography now on windows.  It already includes binaries, which it seems like you already did. 

Hope this helps.

**Comment by xrmx** [comment]
Closing after updating doc regarding cryptography installation and sqlalchemy uri.
