### ISSUE TITLE
Refresh interval isn't sticky within the browser session

### ISSUE THREAD

**Issue by johnbodley** [airbnb/caravel#929]
The refresh interval doesn't seem to persist whenever the page reloads. From a usability standpoint I assumed that once you set this property the refresh interval would persist within the browser session.

**Comment by xrmx** [comment]
Isn't this a dup of #686?

**Comment by alanmcruickshank** [comment]
PR for this feature is here: https://github.com/airbnb/caravel/pull/814

**Comment by trmanish** [comment]
@alanmcruickshank The issue is that this refresh interval works if the browser is open. But in cases where I have built a dashboard and saved it. After coming back again in different tab/window, it again refreshes the whole dashboard which takes time. Can't we keep the saved dashboard as static unless a user wants to refresh it? This makes it less productive as u can't share the dashboard with anyone as they would have to wait for it again.
